/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Controller.DANGNHAPCONTROLLER;
import Controller.ProvinceFetcher;
import static Controller.ProvinceFetcher.fetchProvinceNames;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Admin
 */
public class DK_UI extends javax.swing.JFrame {
String apiUrl = "https://esgoo.net/api-tinhthanh/1/0.htm";
    /**
     * Creates new form DK_UI
     */
    public DK_UI() {
        initComponents();
        ProvinceFetcher tinh = new ProvinceFetcher();
    try {
        String[] provinceNames =  ProvinceFetcher.fetchProvinceNames(apiUrl);
         for (String name : provinceNames) {
                    tFnoiO.addItem(name);
                }
    } catch (Exception ex) {
        Logger.getLogger(DK_UI.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        butDN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tFma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tFnoiO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tFten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tFngay = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tfDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfquyen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ĐĂNG KÍ TÀI KHOẢN");

        butDN.setBackground(new java.awt.Color(51, 153, 255));
        butDN.setText("ĐĂNG KÍ");
        butDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDNActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã số");

        jLabel5.setText("Tỉnh/Thành phố");

        tFnoiO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFnoiOActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ và tên");

        jLabel6.setText("Ngày sinh");

        tFngay.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1716731411521L), null, null, java.util.Calendar.MONTH));

        jLabel4.setText("Số điện thoại");

        jLabel7.setText("Chức vụ");

        tfquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản li" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(butDN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(85, 85, 85)
                                .addComponent(tfquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfDT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tFngay, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(77, 77, 77)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tFten, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                                .addComponent(tFma))
                                            .addGap(15, 15, 15))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(53, 53, 53)
                                    .addComponent(tFnoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tFma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tFten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tFngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFnoiO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfquyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(butDN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean kiemTraNhapLieu(String ma, String ten, Date ngay, String noiO, String soDt, String quyen) {
    // Kiểm tra rỗng
    if (ma.isEmpty() || ten.isEmpty() || noiO.isEmpty() || soDt.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    // Kiểm tra ngày không được là null
    if (ngay == null) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    // Kiểm tra số điện thoại có chứa ký tự khác số không
    if (!soDt.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    // Kiểm tra quyền
    if (!quyen.equals("nv") && !quyen.equals("ql")) {
        JOptionPane.showMessageDialog(null, "Quyền không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    // Nếu tất cả thông số đều hợp lệ
    return true;
}

    private void butDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDNActionPerformed
        String ma = tFma.getText().toString();
         String ten = tFten.getText().toString();
         String sodt = tfDT.getText().toString();
         String quyen;
         if(tfquyen.getSelectedItem().toString().equals("Nhân viên"))
         {
          quyen = "nv";
         }
         else
              quyen = "ql";
         String noio = tFnoiO.getSelectedItem().toString();
        // Lấy giá trị ngày tháng năm từ JSpinner
       Date selectedDate = (java.util.Date) tFngay.getValue();
        Date sqlDate = new java.sql.Date(selectedDate.getTime());
         if (kiemTraNhapLieu(ma, ten, sqlDate, noio, sodt, quyen))
         {
        DANGNHAPCONTROLLER d = new DANGNHAPCONTROLLER();
        if (d.LUUTK(ma, ten, sqlDate, noio, sodt, quyen)==1)
        {
             JOptionPane.showMessageDialog(null, "Đăng kí thành công"); 
        }
        else
             JOptionPane.showMessageDialog(null, "Đăng kí thất bại"); 
         }

    }//GEN-LAST:event_butDNActionPerformed

    private void tFnoiOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFnoiOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFnoiOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DK_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DK_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DK_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DK_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DK_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tFma;
    private javax.swing.JSpinner tFngay;
    private javax.swing.JComboBox<String> tFnoiO;
    private javax.swing.JTextField tFten;
    private javax.swing.JTextField tfDT;
    private javax.swing.JComboBox<String> tfquyen;
    // End of variables declaration//GEN-END:variables
}
