/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;

public class TrangchuUI extends javax.swing.JFrame {
    String role = null;
    int dn=0;
    /**S
     * Creates new form TrangchuUI
     */
    public TrangchuUI() {
        initComponents();
        //internal1.setContentPane(new TK_USERUI().getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPain = new javax.swing.JDesktopPane();
        internal1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MEMUDN = new javax.swing.JMenuItem();
        MENUDK = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        internal1.setVisible(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.png"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("ĐĂNG NHẬP ĐÊ TIẾP TỤC");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("PHẦN MỀM QUẢN LÍ THƯ VIỆN HUIT");

        javax.swing.GroupLayout internal1Layout = new javax.swing.GroupLayout(internal1.getContentPane());
        internal1.getContentPane().setLayout(internal1Layout);
        internal1Layout.setHorizontalGroup(
            internal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internal1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(internal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internal1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internal1Layout.createSequentialGroup()
                        .addGroup(internal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(163, 163, 163))))
        );
        internal1Layout.setVerticalGroup(
            internal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internal1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(109, 109, 109)
                .addComponent(jLabel5)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        desktopPain.setLayer(internal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPainLayout = new javax.swing.GroupLayout(desktopPain);
        desktopPain.setLayout(desktopPainLayout);
        desktopPainLayout.setHorizontalGroup(
            desktopPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internal1)
                .addContainerGap())
        );
        desktopPainLayout.setVerticalGroup(
            desktopPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internal1)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-button.png"))); // NOI18N
        jMenu5.setText("Trang chủ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/stack-of-books.png"))); // NOI18N
        jMenu2.setText("Quản lí sách");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/conflict.png"))); // NOI18N
        jMenu6.setText("Quản lí độc giả");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/technology.png"))); // NOI18N
        jMenu7.setText("Quản lí trả mượn");
        jMenuBar1.add(jMenu7);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account.png"))); // NOI18N
        jMenu3.setText("Quản lí tài khoản");
        jMenu3.setToolTipText("");
        jMenu3.setMargin(new java.awt.Insets(3, 10, 3, 1));

        MEMUDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        MEMUDN.setText("Đăng nhập");
        MEMUDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEMUDNMouseClicked(evt);
            }
        });
        MEMUDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMUDNActionPerformed(evt);
            }
        });
        jMenu3.add(MEMUDN);

        MENUDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/memo.png"))); // NOI18N
        MENUDK.setText("Đăng kí");
        MENUDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUDKActionPerformed(evt);
            }
        });
        jMenu3.add(MENUDK);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar-chart.png"))); // NOI18N
        jMenu1.setText("Thống kê");
        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/settings.png"))); // NOI18N
        jMenu4.setText("Cài đặt");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        TK_USERUI  tk = new TK_USERUI();
        tk.show();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        internal1.setContentPane(new TK_USERUI().getContentPane());    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void MEMUDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMUDNMouseClicked
          internal1.setContentPane(new TK_USERUI().getContentPane()); 
          
          // TODO add your handling code here:
    }//GEN-LAST:event_MEMUDNMouseClicked

    private void MEMUDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMUDNActionPerformed
       internal1.setContentPane(new TK_USERUI().getContentPane());
    }//GEN-LAST:event_MEMUDNActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
         internal1.setContentPane(new tc().getContentPane());       // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void MENUDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUDKActionPerformed
        if(dn==0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập"); 
        }
        else
        {
         if(role.equals("nv"))    
        internal1.setContentPane(new DK_UI().getContentPane());
        else
              JOptionPane.showMessageDialog(null, "Chức vu bạn không thể đăng kí");// TODO add your handling code here:
        }
       
    }//GEN-LAST:event_MENUDKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangchuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangchuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangchuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangchuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangchuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MEMUDN;
    private javax.swing.JMenuItem MENUDK;
    private javax.swing.JDesktopPane desktopPain;
    private javax.swing.JInternalFrame internal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
